package com.timesontransfar.common.framework.core.dynamicdisplay.model.pojo;


/**
 * PubConstraint generated by hbm2java
 * 功能约束对象,这个对象用于表示一个功能中特定控件的约束规则.一个控件可以对应
 * 一个或则多个约束.
 */
public class PubConstraint  implements java.io.Serializable {

    // Fields

	private String ctrlId;
	private java.lang.String constId;
	private java.lang.Integer constType;
	private java.lang.String constName;
	private java.lang.String javaClass="";
	private java.lang.String description;
	private java.lang.String javaBean;
	private java.lang.String method;




    // Constructors

    /** default constructor */
    public PubConstraint() {
    }

    /**
     * constructor with id
     * */
    public PubConstraint(java.lang.String constId) {
        this.constId = constId;
    }




    // Property accessors
    /**
     * 取得约束id 约束id能唯一表示一种约束规则
     */
    public java.lang.String getConstId () {
        return this.constId;
    }
   /**
    * 设置约束id 约束id能唯一表示一种约束规则
    * @param ConstId
    */
   public void setConstId (java.lang.String constId) {
        this.constId = constId;
    }
    /**
     * 取得控件的约束类型,1~50为默认的约束类型.50以后的约束类型
     * 需要配置约束的具体实现方法.
     * @return 约束类型
     */
    public java.lang.Integer getConstType () {
        return this.constType;
    }
   /**
    * 设置控件约束类型
    * @param ConstType 约束类型
    */
   public void setConstType (java.lang.Integer constType) {
        this.constType = constType;
    }
    /**
     * 取得约束规则的名称
     * @return
     */
    public java.lang.String getConstName () {
        return this.constName;
    }
   /**
    * 设置约束名称
    * @param Name
    */
   public void setConstName (java.lang.String name) {
        this.constName = name;
    }
    /**
     * 取得执行约束规则的后台类名称 在约束类型大于50的情况下返回的类名称有效
     * @return 后台执行约束规则的具体类
     */
    public java.lang.String getJavaClass () {
        return this.javaClass;
    }
   /**
    * 设置执行约束规则的具体类 在约束类型大于50的情况下设置类有效
    * @param Javaclass 设置执行约束规则的具体类
    */
   public void setJavaClass (java.lang.String javaclass) {
        this.javaClass = javaclass;
    }



   public java.lang.String getJavaBean () {
       return this.javaBean;
   }
   public void setJavaBean(java.lang.String javaBean) {
       this.javaBean = javaBean;
   }
   public java.lang.String getMethod () {
       return this.method;
   }
   public void setMethod(java.lang.String mehthod) {
       this.method = mehthod;
   }



   /**
    * 取得约束规则的描述信息
    * @return
    */
    public java.lang.String getDescription () {
        return this.description;
    }
  /**
   * 设置约束规则的描述信息
   * @param Description
   */
   public void setDescription (java.lang.String description) {
        this.description = description;
    }
   /**
    * 取得约束规则对应的控件id
    * @return
    */
   public String getCtrlId() {
	   return ctrlId;
   }
   /**
    * 设置要应用约束规则的控件id
    * @param ctrlId 目标控件id
    */
   public void setCtrlId(String ctrlId) {
	   this.ctrlId = ctrlId;
   }

}