server: 
  port: 12118
spring: 
  application: 
    name: custom-activiti
#  main: 
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  devtools: 
    restart: 
      enabled: true   #开启代码保存自动重新启动功能 true:自动重启（开发用这个） false: 不重启（生产用这个）
  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource-mysql: 
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://132.252.220.30:8921/jscsc_test_sheet?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: jscsc_pub_protol
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANFA5LgWT849Vj3iKDjhLPzw3+v28bqcV47J8XCK1qcTLSFrlsvqt8sr3dT8wXy4JWPHebConwOaj1KiukOF+8cCAwEAAQ==
    enpassword: g44bea1qP77WtyUthm0i3uVYwY/+/Y+VJbHRW81PqqHAPX7/0Ij5rdN4IThMJb83XomRoJGM6WMD78y2BxOCYA==
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      minimum-idle: 5
      maximum-pool-size: 12
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1200000
      connection-timeout: 20000
      connection-test-query: select now() from dual
  jscsc-ct-pub: 
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://132.224.250.115:3308/jscsc_ct_sheet?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: app_user
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKTJJDn/oA5T58gqTJxEZdenzzkr09awLmih44DTZe2Xie+CK1/ZX5nKuu2dViHVtLmQ2+nxsSAqmkJitwn3nrsCAwEAAQ==
    enpassword: lFAjL5zcgTejI8Aej9HLIKQHISGgeyn+TvxUNQJv+QBk1wk3o6lIR2xv/0RzhF3J8VyFA3FFc6dOqeikPYRy9A==
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      minimum-idle: 5
      maximum-pool-size: 12
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1200000
      connection-timeout: 20000
      connection-test-query: select now() from dual
      
  # redis 配置
  redis:
    password: xzrMr%F*8h
    cluster:
    - host: 132.224.250.115
      port: 7001
    - host: 132.224.250.116
      port: 7001
    - host: 132.224.250.116
      port: 10911
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: jsdxkfhijklmnopqrstuvwsdasdw
    # 令牌有效期（默认30分钟）
    expireTime: 30  
    
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
#feign客户端配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default: 
        connectTimeout: 60000
        readTimeout: 60000
        #connectTimeout: 5000
        #readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enabled: true
hystrix: 
  threadpool: 
    default: 
      coreSize: 30                      # 核心线程数,并发执行的最大线程数，默认10
      maxQueueSize: 100                 # BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 80   # 控制队列最大阈值,即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
  command: 
    default: 
      execution: 
        timeout: 
          enabled: true
        isolation: 
          strategy: SEMAPHORE
          thread: 
            #timeoutInMilliseconds: 60000
            timeoutInMilliseconds: 60000
      circuitBreaker: 
        sleepWindowInMilliseconds: 100000
        forceClosed: true
  shareSecurityContext: true 
management: 
  endpoints: 
    enabled-by-default: false
    web: 
      exposure: 
        include: '*'

info: 
  app.name: 工作流
  company.name: transfar
  build.artifactId: $project.artifactId$
  build.version: $project.version$
custom:
  logback:
    kafka:
      bootstrap-servers: 132.224.250.115:9092,132.224.250.116:9092
      topic: kf10000-order

ctg:
  cacahe:
    hostAndIp:
      - host: 132.252.220.229
        port: 31046
      - host: 132.252.220.230
        port: 31046
    #最大连接数（空闲+使用中）
    maxTotal: 150
    #最大空闲连接数
    maxIdle: 100
    #保持的最小空闲连接数
    minIdle: 10
    #借出连接时最大的等待时间
    maxWaitMillis: 3000
    soTimeout: 3000
    connectionTimeout: 5000
    userAndPassword: KYF_TEST_KYF_10000H_RES#tk196XyQ6H@qcUlN
  flag: 2