---
- name: add hosts in groups.run
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../file_vars/{{ platform_name }}/common.yml

  tasks:
    - name: check platform_name.
      tags: 
        - kill
        - run
        - run_dr      
      fail:
        msg: "platform_name is not empty.Please write ct_yun or ty_com_yun"
      when: platform_name == ""

    # - name: check project_name.
    #   fail:
    #     msg: "project_name is not empty.Like center-config"
    #   when: project_name == ""

    - name: add hosts in groups.run
      tags: 
        - kill
        - run
        - run_dr
      add_host:
        hostname: "{{ item.hostname }}"
        common: "{{ common }}"
        groups: run
      with_items:
        - "{{ run }}"

- name: run project
  hosts: run
  gather_facts: False

  roles:
    - { role: project, project_name: '{{ project_name }}' }
